### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by pnotequalnp** [coder13/LetsCube#1]
Expected behavior: Styling uses a dark theme

Actual behavior: Styling uses a light theme

Reproduction steps:
1. Start server
2. Open client in browser

Pls add dark theme thx

**Comment by 0003c9fe** [comment]
Some text boxes are unreadable in dark mode, for example
![2020-04-21-1587459220](https://user-images.githubusercontent.com/20267593/79846251-8f2ac500-8401-11ea-8283-f8fdcd74c71b.png)
![2020-04-21-1587459226](https://user-images.githubusercontent.com/20267593/79846265-93ef7900-8401-11ea-9ea5-e16f3df0c761.png)
