### ISSUE TITLE
Let admin permanently Kibitz users

### ISSUE THREAD

**Issue by coder13** [coder13/LetsCube#16]
**Is your feature request related to a problem? Please describe.**
Sometimes, an unwelcome user joins your public server. Or maybe the user left, a bug happened that made them stay, or they just went AFK.

**Describe the solution you'd like**
The admin should be able to kick a user.

**Additional context**
Admins should have some view that lets them manage who's competing.

**Comment by Iurig** [comment]
I'm not sure this should be a separate issue, but since it relates to the same problem, I'm gonna leave it here:

I think the admin should also be able to skip to the next scramble without having to kick/Kibitz every user that hasn't solved yet.

**Comment by coder13** [comment]
The admin actually can skip to the next scramble.
There is a "new scramble" button for the admin.

**Comment by Iurig** [comment]
Ooops, my bad.
