### ISSUE TITLE
Add colors to the layout

### ISSUE THREAD

**Issue by GuidoDipietro** [coder13/LetsCube#19]
Hey! I just tested LetsCube and for the first few minutes I was very confused with the layout. I wasn't able to tell apart the different sections, and I blame it onto the lack of colors.
Even if I really liked the platform, I feel like it has work to be done on the appearance.

Here are some suggestions:

This is an example of how I would re-structure the tables and color them with very light tones (awfully sketched in 2 secs on MsPaint, but the idea is there)
![image](https://user-images.githubusercontent.com/48221146/79771876-c74cdd80-8305-11ea-9717-f50a0d035691.png)

Moreover I'd like it more if the rolling stats were separated from the running session; I implemented that in my sketch moving the position of the "mean" row to be right above the personal stats sector (which, again, I found a bit confusing at first; but I blame myself for that.)

Thicker borders on the edges of each different sector, I reckon, would also help in the visualization.
(And by the way, on the 3-user test we carried out there was some unused space that is kind of bugging me, I marked it in this second sketch.)
![image](https://user-images.githubusercontent.com/48221146/79773315-b309e000-8307-11ea-9e1a-c6f1b5120d34.png)

Not sure what to do with the "Waiting for..." text, I think its location is unimportant.

Excuse the lousy drawings, that was just a quick way to convey my ideas.

As a sidenote, I'm actually very very happy that this platform is getting developed and I'll love to use it as my main one when it's finally released :)

**Comment by coder13** [comment]
Hey, thanks for the detailed feedback.
I like your color choices. 
Not sure what to do with the unused space. What would you do with that. Would you align all the users to the left instead of centering it all?
Here's a mockup of it: 
![image](https://user-images.githubusercontent.com/881394/79777150-b000f680-82eb-11ea-8d2f-3b5fb6e3e18e.png)
I don't like super thick borders. In 2020, thick borders can be ugly. But simple separation of stuff with colors and shadows is what I'll try to do.

**Comment by GuidoDipietro** [comment]
Lovely; I agree that thick borders are not the best looking visual resource, they were just an idea to separate each sector but if that can be done with another approach (like shadows) it would be much better.

Onto the unused space, I'd center the users as much as possible so that each column takes up the same amount of space. I think that's what you did on your mockup.

It's looking much better now :)
