### ISSUE TITLE
Make it easier to tell whether I've solved the current scramble

### ISSUE THREAD

**Issue by Iurig** [coder13/LetsCube#20]
I've noticed that once you solve a scramble, it turns grey, along with the time. But I don't find that easy to tell on a glance, or easy to notice when it changes, on twist the web, the scramble disapeared after the solve, and when a new one popped up, you knew you had to solve again.

I feel like making the scramble disapear could work, especially when we can access previous scrambles, since as of now it is the only way to re scramble the cube. I've thought about making it a lighter grey, but I don't think we can do that in a way that we can both tell at a glance and it's easily readable.

**Comment by coder13** [comment]
Yes, I will need to accomplish this after #13.
