### ISSUE TITLE
Create panel in RoomList to list the number of authenticated users connected

### ISSUE THREAD

**Issue by coder13** [coder13/LetsCube#41]
This is a panel going in the bottom of the room list and it's supposed to list the number of users currently connected to the server. 
Design it similar to the waiting for list in the room page.
The server could simply send out events whenever an authenticated socket connects. The socket reducer can then increment and decrement the number whenever it receives those events.
In `protocol.js`, create `USER_CONNECT` and `USER_DISCONNECT` and simply implement those events and handle them in `middleware.js`

**Comment by wfan19** [comment]
Working on it.

**Comment by wfan19** [comment]
#56 Has been submitted. It has room for improvement but it works for now.
