### ISSUE TITLE
Disable Chat Element for Anonymous Users

### ISSUE THREAD

**Issue by pnotequalnp** [coder13/LetsCube#51]
**Is your feature request related to a problem? Please describe.**
Users who are not logged in can still type messages and "send" them, though these messages are discarded and not actually sent.

**Describe the solution you'd like**
Just disable the chat element, such that they can see it exists, but it disallows interaction.

**Describe alternatives you've considered**
Removing it for anonymous users.

**Comment by wfan19** [comment]
Working on it (Assign to me pls

**Comment by wfan19** [comment]
resolved by #57
