### ISSUE TITLE
Empty room showing "ghosts"

### ISSUE THREAD

**Issue by GuidoDipietro** [coder13/LetsCube#69]
Getting into old rooms may show some users that were there in the past but aren't there anymore.

1. Go to letscube.net
2. Click on "congratulations" room (password is taotaotao)

You will see Tao Yu and Kuruzu14 there, forever. Maybe me (gedos) too.
![image](https://user-images.githubusercontent.com/48221146/81512550-af122200-92f7-11ea-8418-c4beb5934709.png)

(I don't think you need this, but I'm filling it anyway)
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 80.0.3987.163

**Comment by coder13** [comment]
I think this has gone away.
