### ISSUE TITLE
Kicking a user does not prevent them from blocking an existing session

### ISSUE THREAD

**Issue by psifertex** [coder13/LetsCube#81]
**Describe the bug**
When a user lags out and is kicked, they can still block the solves from proceeding.

**To Reproduce**
1. One user on a public room stops responding
2. Kick (or ban) the user
3. The scrambles won't continue

**Expected behavior**
After being kicked or banned the user should not be blocking the session.

**Screenshots**
See the most recent Cubing Dad's stream for vid of it happening.

**Comment by coder13** [comment]
Are you talking about minute 48 of this video?
https://www.twitch.tv/tuptim/video/970791552

**Comment by psifertex** [comment]
The exact timestamp of the issue starts just after the 1hr mark, but yup!

**Comment by coder13** [comment]
I think I fixed it with https://github.com/coder13/LetsCube/commit/da37e2c112e54e6514321caa6ba8c1c0da314f64
Will close once merged into master.
